### PR TITLE
TG-20, TG-31 single event get endpoint and event meetings endpoint

### PR DESCRIPTION
**Pull request by lychanl**

### CODE REVIEW

**Comment by Grushenko** [comment]
Your implementation do not return full event object (with nested `meetings` fields). You have to define separate DTO with `meetings` list (simmilar to `EventRequestDto`)

**Comment by lychanl** [comment]
> Your implementation do not return full event object (with nested `meetings` fields). You have to define separate DTO with `meetings` list (simmilar to `EventRequestDto`)

Fixed

**Comment by lychanl** [comment]
@Grushenko on second thought, shouldn't meetings be returned by a separate endpoint as referenced by TG-31 task?

**Comment by Grushenko** [comment]
> @Grushenko on second thought, shouldn't meetings be returned by a separate endpoint as referenced by TG-31 task?

As for this there is no use case when single event should be fetched from BE without geting meetings, and limiting number HTTP requests is a good practice.
TG-31 was created probably as missunderstanding (as we discussed whole single event fetch before to include meetings list).

**Comment by lychanl** [comment]
OK, so should I revert to a single endpoint that returns both event and its meetings?

**Comment by Delebrith** [comment]
> 
> 
> > @Grushenko on second thought, shouldn't meetings be returned by a separate endpoint as referenced by TG-31 task?
> 
> As for this there is no use case when single event should be fetched from BE without geting meetings, and limiting number HTTP requests is a good practice.
> TG-31 was created probably as missunderstanding (as we discussed whole single event fetch before to include meetings list).

That is true, I forgot that we decided to return meetings in single event response, so I created the TG-31 task. I'm sorry for the trouble.

**Comment by Delebrith** [comment]
> 
> 
> OK, so should I revert to a single endpoint that returns both event and its meetings?

yes, please.

**Comment by Grushenko** [comment]
> OK, so should I revert to a single endpoint that returns both event and its meetings?

Actually current version on this branch returns single event with lists as it should. Perhaps that was caused by my cleanup rebase on this branch (to remove all merges). @lychanl you could check if that version is OK and rebase this PR.

**Pull request merged**
